spring.application.name=orderservice
server.port=8080

# Logging Configuration
logging.level.com.stofina.orderservice=INFO
logging.level.root=INFO
logging.file.name=order-lifecycle.log
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %level %logger{36} - %msg%n
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss.SSS} %5level --- [%15.15t] %-40.40logger{39} : %msg%n
